### PR TITLE
Camera focus

### PR DESCRIPTION
**Pull request by Roccy**
Toggle button added to set focus mode to MACRO. (Might be fun to add a check if MACRO is available, and show if not available)

Set fixed size for the picture, 720x480. This can be changed to adjust to what the phone is able to.

Mostly, this pull request can be used to make an APK for demo purposes right now.

### CODE REVIEW

**Comment by jorenham** [comment]
```
org.fingerblox.fingerblox E/AndroidRuntime: FATAL EXCEPTION: main
                                            Process: org.fingerblox.fingerblox, PID: 18693
                                            java.lang.RuntimeException: setParameters failed
                                                at android.hardware.Camera.native_setParameters(Native Method)
                                                at android.hardware.Camera.setParameters(Camera.java:1984)
                                                at org.fingerblox.fingerblox.CameraView.setFixedFocusDistance(CameraView.java:75)
                                                at org.fingerblox.fingerblox.CameraView.initializeCamera(CameraView.java:54)
                                                at org.opencv.android.JavaCameraView.connectCamera(JavaCameraView.java:247)
                                                at org.opencv.android.CameraBridgeViewBase.onEnterStartedState(CameraBridgeViewBase.java:360)
                                                at org.opencv.android.CameraBridgeViewBase.processEnterState(CameraBridgeViewBase.java:321)
                                                at org.opencv.android.CameraBridgeViewBase.checkCurrentState(CameraBridgeViewBase.java:313)
                                                at org.opencv.android.CameraBridgeViewBase.enableView(CameraBridgeViewBase.java:229)
                                                at org.fingerblox.fingerblox.MainActivity$1.onManagerConnected(MainActivity.java:46)
                                                at org.opencv.android.AsyncServiceHelper$3.onServiceConnected(AsyncServiceHelper.java:319)
                                                at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1335)
                                                at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1352)
                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                at android.os.Looper.loop(Looper.java:158)
                                                at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                at java.lang.reflect.Method.invoke(Native Method)
                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Review by jrauhamaa — APPROVED** [review]

**Review by jorenham — CHANGES_REQUESTED** [review]
Doesn't work on my galaxy S5 :cry: 
See the stacktrace
Maybe you could display a warning message if macro is not supported and then continue with a different setting?

**Comment by Roccy** [comment]
Ah, that means I'll have to check the phone for if it allows macro or if it's the correct image size. Will check after dinner

**Comment by jorenham** [comment]
@Roccy Or you do a `try catch` :+1:

**Review by jorenham — APPROVED** [review]

**Pull request merged**
