### PR TITLE
Change overlay from rectangle to ellipse. Focus the camera on the finger. Take pictures.

### PR DESCRIPTION
**Pull request by jrauhamaa**

### CODE REVIEW

**Comment by jorenham** [comment]
Needs a rebase?

**Comment by Roccy** [comment]
The focus mode and area list do not get updated. It needs a call to `mCamera.setParameters(parameters)` and the focus rectangle does not correspond with the overlay ellipse (overlay works with pixels and camera with -1000,1000. I've already fixed it.

**Comment by jorenham** [comment]
Can be closed now right?

**Comment by Roccy** [comment]
Unless there is something from the latest commit from @jrauhamaa that needs to be in there, all has been merged with another pull-request. Closing for now.

**Pull request closed without merging**
